### ISSUE TITLE
Falta documentación.

### ISSUE THREAD

**Issue by lauramcastro** [Kaizo88/prac3-vvs1516#1]
Xerades o JavaDoc (que non deberiades subir ao repositorio: lembrade, todo que se poida xerar, non debería estar ocupando sitio nun repositorio, e ter que descargarse/compararse cada vez que nos comunicamos cunha copia remota), pero non tedes ningún diagrama UML que represente a estrutura actual da implementación (a evolución do diagrama do enunciado).

**Comment by pablodiazv** [comment]
Corregido, eliminado javadoc del repositorio y subido el diagrama UML
