### ISSUE TITLE
Uso del equals en el metodo agregar

### ISSUE THREAD

**Issue by Cryx7** [Kaizo88/prac3-vvs1516#5]
Al no estar redefinido el equals y hashcode compara por referencia y no por valor.
Ademas, se recomienda parsear adecuadamente los strings antes de compararlos si se quiere distinguir minusculas y mayusculas en los titulos.

**Comment by josepallas** [comment]
Cúal sería el método agregar incorrecto, el de contenido o el de servidor ?
Y en cualquiera de los casos comparamos dos strings  por lo que no haría falta redefinir el equals.
A la hora de comparar con mayúsculas a que caso os referís? Si es en caso de agregar en emisora usamos el equals para ver si tienen exactamente el mismo título(incluído las mayúsculas)

**Comment by Cryx7** [comment]
Teneis razon con lo del equals... y en cuanto a su uso en agregar emisora, si el comportamiento es el de comparar 2 titulos "exactamente iguales" ps la implmentacion es correcta.

**Comment by lauramcastro** [comment]
En esta issue mezcláronse dous aspectos: a comparación sen redefinición de método equals (por referencia) e a comparación sensible a maiúsculas e minúsculas. O axeitado sería que tiveran sido dúas issues diferentes.
