### ISSUE TITLE
Uso de constantes na implementación do servidor

### ISSUE THREAD

**Issue by javilg** [Kaizo88/prac3-vvs1516#8]
Para levar a conta do número máximo de reproducións dun token no método alta(), e para contar o número de contidos entre anuncios en buscar(), se se emplean constantes, no caso de cambiar eses valores, farase nun único punto, ademais de axudar a lexibilidade do código.

**Comment by diegocampelo** [comment]
Añadidas ambas constantes. 

Closed.
